CREATE TABLE produto_tb
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255)                            NOT NULL,
    preco        FLOAT                                   NOT NULL,
    tipo_item_id BIGINT,
    CONSTRAINT pk_produto_tb PRIMARY KEY (id)
);

ALTER TABLE produto_tb
    ADD CONSTRAINT FK_PRODUTO_TB_ON_TIPO_ITEM FOREIGN KEY (tipo_item_id) REFERENCES tipo_item_tb (id);