CREATE TABLE venda_tb
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_venda  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    valor_total FLOAT                                   NOT NULL,
    CONSTRAINT pk_venda_tb PRIMARY KEY (id)
);