CREATE TABLE item_venda_tb
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade     INTEGER                                 NOT NULL,
    preco_unitario DECIMAL(10, 2)                          NOT NULL,
    venda_id       BIGINT,
    produto_id     BIGINT,
    CONSTRAINT pk_item_venda_tb PRIMARY KEY (id)
);

ALTER TABLE item_venda_tb
    ADD CONSTRAINT FK_ITEM_VENDA_TB_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produto_tb (id);

ALTER TABLE item_venda_tb
    ADD CONSTRAINT FK_ITEM_VENDA_TB_ON_VENDA FOREIGN KEY (venda_id) REFERENCES venda_tb (id);