CREATE TABLE estoque_tb
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade BIGINT                                  NOT NULL,
    produto_id BIGINT,
    CONSTRAINT pk_estoque_tb PRIMARY KEY (id)
);

ALTER TABLE estoque_tb
    ADD CONSTRAINT uc_estoque_tb_produto UNIQUE (produto_id);

ALTER TABLE estoque_tb
    ADD CONSTRAINT FK_ESTOQUE_TB_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produto_tb (id);