spring:
  application:
    name: ${APP_NAME:back}

  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE:update}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true